#!/usr/bin/env node
/**
 * Regenerate the committed single-file plugin bundle (W3, ADR 0011 §5/§6).
 *
 * Run via `npm run build:plugin` (wired into `postbuild` and regenerated by
 * `opencode/plugins/arggon/bundle.test.ts`). Deterministic: the same source and
 * TypeScript version produce byte-identical output, which `cli/src/plugin-copy.test.ts`
 * drift-gates (assert-before-write) and `npm run check:plugin` enforces in CI.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { packageRoot } from "./package-assets.js";
import { PLUGIN_BUNDLE, buildPluginBundle } from "./plugin-bundle.js";

const root = packageRoot();
const { code, modules } = buildPluginBundle(root);
const dest = join(root, ...PLUGIN_BUNDLE.split("/"));
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, code, "utf8");
console.log(
  `build:plugin — ${modules.length} modules inlined, ${Buffer.byteLength(code, "utf8")} bytes -> ${PLUGIN_BUNDLE}`,
);
