import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { isItemType, type ItemType } from "./ids.js";

/** Latest task-tree convention version written by `arggon init` (docs/convention.md). */
export const CONVENTION_VERSION = 3;

/** Version assumed when `tasks/.convention.yml` is missing or unparseable (omit file = 0). */
export const CONVENTION_VERSION_DEFAULT = 0;

/**
 * Read the tree convention version from `<dir>/tasks/.convention.yml`.
 * Returns CONVENTION_VERSION_DEFAULT when the file is missing or has no
 * parseable `version: N` line (per docs/json-output.md: omit file = 0).
 */
export function readConventionVersion(dir: string): number {
  const path = join(dir, "tasks/.convention.yml");
  if (!existsSync(path)) return CONVENTION_VERSION_DEFAULT;
  try {
    const raw = readFileSync(path, "utf8");
    const match = raw.match(/^version\s*:\s*(\d+)/m);
    if (!match) return CONVENTION_VERSION_DEFAULT;
    const parsed = Number.parseInt(match[1] ?? "", 10);
    return Number.isFinite(parsed) ? parsed : CONVENTION_VERSION_DEFAULT;
  } catch {
    return CONVENTION_VERSION_DEFAULT;
  }
}

/** Default `branch_patterns` (docs/convention.md): feat/ everywhere, fix/ for bugs. */
export const DEFAULT_BRANCH_PATTERNS: Record<ItemType, string> = {
  initiative: "feat/{id}",
  epic: "feat/{id}",
  story: "feat/{id}",
  task: "feat/{id}",
  bug: "fix/{id}",
};

/** `x-playbooks` namespaced extension options (story-tech-playbooks). */
export type PlaybooksConfig = {
  /**
   * Stale threshold for `arggon playbook status`, in days, from
   * `x-playbooks.max-age-days`. `null` when unset (the command applies its
   * own default of 90).
   */
  maxAgeDays: number | null;
};

/** `x-tracker` namespaced extension options (story-tracker-hygiene). */
export type TrackerConfig = {
  /**
   * Auto-commit of tracker mutations from `x-tracker.auto-commit`
   * (create/comment/adopt/cleanup --prune). `null` when unset (callers apply
   * the built-in default of true; a `--no-commit` CLI flag still wins).
   */
  autoCommit: boolean | null;
  /**
   * Claim-steal arming from `x-tracker.allow-steal` (bug-cli-steal-not-gated).
   * `null` (unset) and `false` both leave `update --steal` refused with an
   * actionable message; only an explicit `true` arms the interactive,
   * human-only steal flow.
   */
  allowSteal: boolean | null;
};

/** `x-import` namespaced extension options (task-import-type-mapping). */
export type ImportConfig = {
  /**
   * GitHub label -> work-item type mapping from `x-import.label-types`
   * (keys matched exactly against the slugified issue labels). `null` when
   * unset (the import applies its built-in default: `bug` -> bug, everything
   * else -> task). Values are validated as work-item types at parse time;
   * the import itself only accepts leaf types (`task`/`bug`).
   */
  labelTypes: Record<string, ItemType> | null;
};

/** `x-worktree` namespaced extension options (task-start-post-hook). */
export type WorktreeConfig = {
  /**
   * Shell command from `x-worktree.post-start`, run inside a freshly created
   * worktree after a successful `arggon start --worktree` (cwd = the worktree
   * root). `null` when unset (the start is a no-op for the hook; `--no-hook`
   * skips it per invocation).
   */
  postStart: string | null;
  /**
   * Shell variant from `x-worktree.post-start-shell` (task-post-start-env):
   * `"inherit"` (default) runs the hook via `sh -c` with the invoking arggon
   * process environment; `"login"` runs it via the user's login shell
   * (`$SHELL -lc`) so toolchains installed through profile files (rustup's
   * ~/.cargo/env, mise, asdf) land on PATH. `null` when unset (= inherit).
   * The `--post-start-shell` start flag overrides per invocation.
   */
  postStartShell: "inherit" | "login" | null;
};

/**
 * One generated-doc provenance record (`x-generated` namespaced extension,
 * story-adoption-state): destination path -> entry, written by
 * `generateDocs`/`init` after stamping the file with its marker comment.
 */
export type GeneratedEntry = {
  /** Source template, package-root relative (e.g. "docs/AGENTS.md"). */
  template: string;
  /** Checksum of the file as generated, "sha256:<hex>" (marker included). */
  checksum: string;
  /** ArggonManager version that generated the file. */
  arggonVersion: string;
  /** ISO-8601 timestamp of the generating run. */
  generatedAt: string;
  /**
   * True when `arggon adopt --ack` sanctioned the current content as the
   * baseline (bug-ack-baseline-regen-loss): the entry is adopter-owned
   * sanctioned-diverged content and is NEVER regenerated by later `init`
   * re-runs, even though the checksum matches the recorded baseline.
   */
  acknowledged?: boolean;
};

export type ConventionConfig = {
  version: number;
  /** Per-type branch patterns; always complete (missing keys fall back to defaults). */
  branchPatterns: Record<ItemType, string>;
  /** Named saved views (`x-views` extension key): view name -> filter expression. */
  views: Record<string, string>;
  /** Technology-playbook options (`x-playbooks` extension key). */
  playbooks: PlaybooksConfig;
  /** Tracker-hygiene options (`x-tracker` extension key). */
  tracker: TrackerConfig;
  /** Issue-import options (`x-import` extension key). */
  import: ImportConfig;
  /** Worktree-bootstrap options (`x-worktree` extension key). */
  worktree: WorktreeConfig;
  /**
   * Generated-doc provenance (`x-generated` extension key): destination path
   * (posix, relative to the repo root) -> provenance entry.
   */
  generated: Record<string, GeneratedEntry>;
};

function stripQuotes(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

/**
 * Parse `tasks/.convention.yml` (line-oriented, no YAML dependency).
 * Unknown top-level keys are ignored for forward compatibility;
 * `x-views` (saved views), `x-playbooks` (playbook staleness options),
 * `x-tracker` (tracker-hygiene options), `x-import` (issue-import options),
 * `x-worktree` (worktree-bootstrap options), and `x-generated` (generated-doc
 * provenance) are the official namespaced extensions.
 * Throws with file context on malformed `branch_patterns`, `x-views`,
 * `x-playbooks`, `x-tracker`, `x-import`, or `x-worktree`; `x-generated`
 * parses tolerantly (machine-written state).
 */
export function parseConventionConfig(
  raw: string,
  sourcePath = "tasks/.convention.yml",
): ConventionConfig {
  const branchPatterns: Record<ItemType, string> = { ...DEFAULT_BRANCH_PATTERNS };
  const views: Record<string, string> = {};
  const playbooks: PlaybooksConfig = { maxAgeDays: null };
  const tracker: TrackerConfig = { autoCommit: null, allowSteal: null };
  const generated: Record<string, GeneratedEntry> = {};
  const importLabelTypes: Record<string, ItemType> = {};
  let importHasLabelTypes = false;
  const worktree: WorktreeConfig = { postStart: null, postStartShell: null };
  let version = CONVENTION_VERSION_DEFAULT;
  let section: string | null = null;
  let generatedDest: string | null = null;
  let importOption: string | null = null;

  for (const line of raw.split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const indent = line.length - line.trimStart().length;
    const idx = line.indexOf(":");
    if (idx === -1) {
      throw new Error(`${sourcePath}: invalid line ${JSON.stringify(line)}`);
    }
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    if (indent === 0) {
      section = null;
      generatedDest = null;
      importOption = null;
      if (key === "version") {
        const parsed = Number.parseInt(value, 10);
        if (Number.isFinite(parsed)) version = parsed;
      } else if (key === "branch_patterns") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'branch_patterns' must be a mapping, one type per line`);
        }
        section = "branch_patterns";
      } else if (key === "x-views") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'x-views' must be a mapping, one view per line`);
        }
        section = "x-views";
      } else if (key === "x-playbooks") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'x-playbooks' must be a mapping, one option per line`);
        }
        section = "x-playbooks";
      } else if (key === "x-tracker") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'x-tracker' must be a mapping, one option per line`);
        }
        section = "x-tracker";
      } else if (key === "x-import") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'x-import' must be a mapping, one option per line`);
        }
        section = "x-import";
      } else if (key === "x-worktree") {
        if (value !== "") {
          throw new Error(`${sourcePath}: 'x-worktree' must be a mapping, one option per line`);
        }
        section = "x-worktree";
      } else if (key === "x-generated") {
        if (value !== "") {
          throw new Error(
            `${sourcePath}: 'x-generated' must be a mapping, one destination per line`,
          );
        }
        section = "x-generated";
      }
      continue;
    }
    if (section === "x-generated") {
      // Namespaced machine-written state (story-adoption-state): tolerant
      // parse — unknown fields are ignored (ignore-unknown) and incomplete
      // entries are kept as-is (a missing checksum simply never matches, so
      // the file reports as adopter-modified). Hand edits must never break
      // init or doctor.
      if (indent <= 2) {
        const dest = stripQuotes(key);
        generatedDest = dest !== "" ? dest : null;
        if (generatedDest !== null && !(generatedDest in generated)) {
          generated[generatedDest] = {
            template: "",
            checksum: "",
            arggonVersion: "",
            generatedAt: "",
          };
        }
        continue;
      }
      if (generatedDest === null) continue;
      const entry = generated[generatedDest]!;
      if (key === "template") entry.template = stripQuotes(value);
      else if (key === "checksum") entry.checksum = stripQuotes(value);
      else if (key === "arggonVersion") entry.arggonVersion = stripQuotes(value);
      else if (key === "generatedAt") entry.generatedAt = stripQuotes(value);
      else if (key === "acknowledged") entry.acknowledged = value === "true";
      // Unknown nested keys are ignored.
      continue;
    }
    if (section === "x-playbooks") {
      // Namespaced extension: unknown nested keys are ignored (ignore-unknown),
      // only the official `max-age-days` option is read.
      if (key !== "max-age-days") continue;
      if (!/^\d+$/.test(value) || Number.parseInt(value, 10) <= 0) {
        throw new Error(
          `${sourcePath}: 'max-age-days' must be a positive integer (got ${JSON.stringify(value)})`,
        );
      }
      playbooks.maxAgeDays = Number.parseInt(value, 10);
      continue;
    }
    if (section === "x-tracker") {
      // Namespaced extension: unknown nested keys are ignored (ignore-unknown),
      // the official options are `auto-commit` (tracker hygiene) and
      // `allow-steal` (claim-steal arming, bug-cli-steal-not-gated).
      if (key === "allow-steal") {
        if (value !== "true" && value !== "false") {
          throw new Error(
            `${sourcePath}: 'allow-steal' must be a boolean (got ${JSON.stringify(value)})`,
          );
        }
        tracker.allowSteal = value === "true";
        continue;
      }
      if (key !== "auto-commit") continue;
      if (value !== "true" && value !== "false") {
        throw new Error(
          `${sourcePath}: 'auto-commit' must be a boolean (got ${JSON.stringify(value)})`,
        );
      }
      tracker.autoCommit = value === "true";
      continue;
    }
    if (section === "x-import") {
      // Namespaced extension (task-import-type-mapping): unknown option keys
      // are ignored (ignore-unknown); the official `label-types` option is a
      // nested mapping of GitHub label -> work-item type.
      if (indent <= 2) {
        importOption = key === "label-types" ? "label-types" : null;
        if (importOption !== null) {
          // An explicitly declared label-types option is "set" even with zero
          // entries (empty mapping = no label mapping, replacing the default).
          importHasLabelTypes = true;
          if (value !== "") {
            throw new Error(`${sourcePath}: 'label-types' must be a mapping, one label per line`);
          }
        }
        continue;
      }
      if (importOption !== "label-types") continue;
      const label = stripQuotes(key);
      if (!label) {
        throw new Error(`${sourcePath}: invalid x-import entry ${JSON.stringify(line)}`);
      }
      if (label in importLabelTypes) {
        throw new Error(`${sourcePath}: duplicate label '${label}' in x-import.label-types`);
      }
      const mapped = stripQuotes(value);
      if (!isItemType(mapped)) {
        throw new Error(
          `${sourcePath}: 'label-types' values must be work-item types ` +
            `(initiative | epic | story | task | bug), got ${JSON.stringify(value)} for label '${label}'`,
        );
      }
      importLabelTypes[label] = mapped;
      importHasLabelTypes = true;
      continue;
    }
    if (section === "x-worktree") {
      // Namespaced extension (task-start-post-hook): unknown nested keys are
      // ignored (ignore-unknown); the official `post-start` option is a shell
      // command run inside a freshly created worktree.
      if (key === "post-start-shell") {
        // Shell variant (task-post-start-env): "inherit" (default) or "login"
        // ($SHELL -lc, sources profile files so rustup/mise/asdf toolchains
        // are on PATH). Anything else is a parse error.
        const shell = stripQuotes(value);
        if (shell !== "inherit" && shell !== "login") {
          throw new Error(
            `${sourcePath}: 'post-start-shell' must be "inherit" or "login" (got ${JSON.stringify(value)})`,
          );
        }
        worktree.postStartShell = shell;
        continue;
      }
      if (key !== "post-start") continue;
      const command = stripQuotes(value);
      if (!command) {
        throw new Error(
          `${sourcePath}: 'post-start' must be a non-empty string (got ${JSON.stringify(value)})`,
        );
      }
      worktree.postStart = command;
      continue;
    }
    if (section === "x-views") {
      if (!key) {
        throw new Error(`${sourcePath}: invalid x-views entry ${JSON.stringify(line)}`);
      }
      if (key in views) {
        throw new Error(`${sourcePath}: duplicate view '${key}' in x-views`);
      }
      const expr = stripQuotes(value);
      if (!expr) {
        throw new Error(`${sourcePath}: empty expression for view '${key}'`);
      }
      views[key] = expr;
      continue;
    }
    if (section !== "branch_patterns") continue;
    if (!isItemType(key)) {
      throw new Error(
        `${sourcePath}: unknown type '${key}' in branch_patterns (expected: initiative | epic | story | task | bug)`,
      );
    }
    const pattern = stripQuotes(value);
    if (!pattern) {
      throw new Error(`${sourcePath}: empty pattern for type '${key}'`);
    }
    if (!pattern.includes("{id}")) {
      throw new Error(
        `${sourcePath}: pattern for type '${key}' must contain an {id} placeholder (got ${JSON.stringify(pattern)})`,
      );
    }
    branchPatterns[key] = pattern;
  }

  return {
    version,
    branchPatterns,
    views,
    playbooks,
    tracker,
    import: { labelTypes: importHasLabelTypes ? importLabelTypes : null },
    worktree,
    generated,
  };
}

/** Read and parse `<dir>/tasks/.convention.yml`. Missing file yields version 0 + defaults. */
export function readConventionConfig(dir: string): ConventionConfig {
  const path = join(dir, "tasks/.convention.yml");
  if (!existsSync(path)) {
    return {
      version: CONVENTION_VERSION_DEFAULT,
      branchPatterns: { ...DEFAULT_BRANCH_PATTERNS },
      views: {},
      playbooks: { maxAgeDays: null },
      tracker: { autoCommit: null, allowSteal: null },
      import: { labelTypes: null },
      worktree: { postStart: null, postStartShell: null },
      generated: {},
    };
  }
  return parseConventionConfig(readFileSync(path, "utf8"), path);
}

/**
 * Tolerant read of the `x-generated` provenance state. Unlike
 * `readConventionConfig` this never throws: a missing file or a malformed
 * `.convention.yml` yields an empty state (docs then count as
 * adopter-modified — the conservative default).
 */
export function readGeneratedState(dir: string): Record<string, GeneratedEntry> {
  const path = join(dir, "tasks/.convention.yml");
  if (!existsSync(path)) return {};
  try {
    return parseConventionConfig(readFileSync(path, "utf8"), path).generated;
  } catch {
    return {};
  }
}

/** Serialize one quoted YAML scalar (double quotes, backslash-escaped). */
function yamlQuote(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/** Quote a mapping key when it is not a plain safe path token. */
function yamlKey(key: string): string {
  return /^[A-Za-z0-9._/-]+$/.test(key) ? key : yamlQuote(key);
}

/**
 * Serialize the `x-generated` section (destinations sorted) for the given
 * provenance entries. Empty entries serialize as no section at all.
 */
export function serializeGeneratedSection(entries: Record<string, GeneratedEntry>): string[] {
  const dests = Object.keys(entries).sort();
  if (dests.length === 0) return [];
  const lines: string[] = ["x-generated:"];
  for (const dest of dests) {
    const entry = entries[dest]!;
    lines.push(`  ${yamlKey(dest)}:`);
    lines.push(`    template: ${yamlQuote(entry.template)}`);
    lines.push(`    checksum: ${yamlQuote(entry.checksum)}`);
    lines.push(`    arggonVersion: ${yamlQuote(entry.arggonVersion)}`);
    lines.push(`    generatedAt: ${yamlQuote(entry.generatedAt)}`);
    // Acknowledged baselines (bug-ack-baseline-regen-loss) are recorded only
    // when set, so sections written before the flag stay byte-identical.
    if (entry.acknowledged) lines.push(`    acknowledged: true`);
  }
  return lines;
}

/**
 * Splice a fresh `x-generated` section into raw `.convention.yml` text,
 * replacing any existing section. Everything outside the section — version,
 * branch_patterns, x-views, x-playbooks, comments, blank lines, unknown keys —
 * is preserved byte-for-byte. With no entries, an existing section is removed.
 */
export function updateGeneratedSection(
  raw: string,
  entries: Record<string, GeneratedEntry>,
): string {
  const lines = raw.split(/\r?\n/);
  const start = lines.findIndex((line) => /^x-generated:\s*$/.test(line));
  if (start !== -1) {
    let end = start + 1;
    while (end < lines.length && (lines[end] === "" || (lines[end]!.length - lines[end]!.trimStart().length) > 0)) {
      end++;
    }
    lines.splice(start, end - start);
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  const section = serializeGeneratedSection(entries);
  if (section.length === 0) {
    return lines.length > 0 ? `${lines.join("\n")}\n` : "";
  }
  if (lines.length > 0) lines.push("");
  return `${[...lines, ...section].join("\n")}\n`;
}

/** Resolve a branch pattern for an item (`{id}` required, `{type}` optional). */
export function resolveBranchName(pattern: string, item: { id: string; type: ItemType }): string {
  return pattern.replaceAll("{id}", item.id).replaceAll("{type}", item.type);
}
