/**
 * `arggon doctor` — installation state report (story-adoption-state,
 * task-doctor-command). Report-only, exit 0: answers "is ArggonManager
 * installed here, and in what shape" from the same sources init writes —
 * tasks/.convention.yml (convention version, x-generated provenance) and the
 * work-item tree (tracker counts). Never writes anything.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, type Dirent } from "node:fs";
import { join } from "node:path";
import { readConventionConfig, readConventionVersion } from "./convention.js";
import {
  checksumMatches,
  currentGeneratedTemplatesFrom,
  normalizeEol,
  OPENCODE_CONFIG_CANDIDATES,
  renderGeneratedDoc,
  resolveProjectName,
} from "./docs.js";
import { loadItems } from "./items.js";
import { measureBudget, formatBudgetLines, type BudgetResult } from "./measure.js";
import { findTasksDir, repoRootFromTasks, bundledTemplatesDir } from "./paths.js";
import { sanitizeHumanText, sanitizeHumanValue } from "./sanitize.js";

// The sanitizer implementation moved to sanitize.ts (bug-cli-error-output-injection
// F1) so the CLI error channel shares it; re-exported for existing consumers.
export { MAX_HUMAN_VALUE_CHARS } from "./sanitize.js";

export type DoctorDocs = {
  /** Total x-generated provenance entries. */
  managed: number;
  /** Files whose checksum still matches the recorded one. */
  untouched: number;
  /** Files on disk whose checksum differs from the recorded one. */
  modified: number;
  /**
   * Entries acknowledged via `arggon adopt --ack` (bug-ack-baseline-regen-loss):
   * sanctioned-diverged baselines — healthy, and never regenerated by init.
   */
  acknowledged: number;
  /**
   * Acknowledged entries whose CURRENT checksum differs from the recorded
   * acked baseline (bug-ack-drift-promise): a hand edit landed after the ack.
   * Informational only — the file stays adopter-owned (never `modified`,
   * never regenerated by init); this bucket just makes the drift visible.
   */
  acknowledgedDrifted: number;
  /** State entries whose template no longer exists in the current bundle. */
  stale: number;
  /** State entries whose destination file is absent. */
  missing: number;
  /**
   * Managed docs whose CURRENT template render differs from the on-disk
   * content (task-doctor-outdated-bucket): the upstream template moved since
   * the doc was generated/acked, so it is not receiving upstream
   * improvements. Orthogonal to the untouched/modified/acknowledged buckets
   * (upstream moved regardless of local state); docs in `stale` (template no
   * longer generated) or `missing` are never outdated, and a missing or
   * unreadable template file counts as "cannot decide" — not outdated,
   * never a throw.
   */
  outdated: number;
  /**
   * Destinations counted in `outdated` (posix, relative to root) — the
   * per-destination detail behind the count.
   */
  outdatedDocs: string[];
};

/**
 * Git state of the target tree (bug-init-git-doctor-blindspot): report-only —
 * branch/worktree/push/PR flows and the pre-commit validate hook all depend on
 * git, so doctor surfaces whether they are even possible here. `dirty` and
 * `remote` are null when the tree is not a git repository.
 */
export type DoctorGit = {
  isRepo: boolean;
  /** Working tree has uncommitted changes (status --porcelain non-empty); null when not a repo. */
  dirty: boolean | null;
  /** URL of the `origin` remote (else the first remote); null when not a repo or no remote. */
  remote: string | null;
};

/**
 * OpenCode integration state (task-opencode-v2-doctor): additive, report-only
 * answer to "does this tree carry a working OpenCode V2 seam?" — which config
 * files exist, which V1-shaped keys they still carry, which generated
 * `.opencode/`/`.agents/skills` artifacts are on disk (names only), and
 * whether the arggon MCP server is registered natively (`mcp.servers.arggon`)
 * or only in `.mcp.json` (which V2 does not read). Every path is either fixed
 * or one non-recursive readdir, and every list is explicitly capped — no
 * recursive scans, no writes, exit code unchanged.
 */
export type DoctorOpenCode = {
  /**
   * Present OpenCode config files (posix, relative to the probed root), in the
   * candidate order of the shared `OPENCODE_CONFIG_CANDIDATES` export
   * (cli/src/docs.ts, opencode-seam-010; MINOR-3, PR #324 review): the list is
   * imported, not mirrored. Unlike `findOpenCodeConfig` (first ADOPTER match
   * only — init uses it to decide whether to generate a config), doctor reports
   * every present file; an unreadable or malformed one still appears here, it
   * just contributes no findings.
   */
  configs: string[];
  /**
   * V1-shaped config keys (task-opencode-v2-doctor): top-level `enabled`,
   * `autoupdate`, `permission`, `tools`, `maxSteps`, plus MCP servers nested
   * directly under `mcp` — V2 requires `mcp.servers`, and V2-valid children
   * (`mcp.timeout`) are never flagged. One finding per config file with hits.
   */
  v1: {
    findings: Array<{ file: string; keys: string[] }>;
    /** True when a file had more hits than MAX_OPENCODE_V1_KEYS_PER_FILE. */
    truncated: boolean;
  };
  /** Generated seam artifacts on disk (task-opencode-v2-doctor; names only). */
  artifacts: {
    /** `opencode.jsonc` exists — the config `arggon init` generates when no adopter config exists. */
    config: boolean;
    /** Agent names (`.md` stems) under `.opencode/agents`, sorted. */
    agents: string[];
    /** Command names (`.md` stems) under `.opencode/commands`, sorted. */
    commands: string[];
    /** Skill directory names under `.agents/skills`, sorted. */
    skills: string[];
    /** True when one of the name lists hit MAX_OPENCODE_NAMES and was cut. */
    truncated: boolean;
  };
  mcp: {
    /** A present OpenCode config registers `mcp.servers.arggon`. */
    native: boolean;
    /** `.mcp.json` registers the `arggon` server under `mcpServers`. */
    mcpJson: boolean;
    /** Actionable stanza/path hint when only `.mcp.json` exists; `null` otherwise. */
    hint: string | null;
  };
};

/** V1 top-level keys V2 renamed or dropped (task-opencode-v2-doctor). */
const OPENCODE_V1_KEYS = ["enabled", "autoupdate", "permission", "tools", "maxSteps"] as const;

/** Documented V2 children of `mcp` (https://opencode.ai/v2/docs/mcp-servers/, 2026-09-17). */
const OPENCODE_V2_MCP_KEYS = new Set(["servers", "timeout"]);

/** Per-list cap for named artifacts — the JSON block stays bounded. */
export const MAX_OPENCODE_NAMES = 50;

/** Per-file cap for V1-shaped key findings. */
export const MAX_OPENCODE_V1_KEYS_PER_FILE = 20;

/**
 * Actionable hint when the arggon MCP server exists only in `.mcp.json`
 * (which OpenCode V2 does not read): the exact stanza and path to add.
 */
export const OPENCODE_MCP_HINT =
  'OpenCode V2 does not read .mcp.json — add "mcp.servers.arggon" in opencode.json(c): ' +
  '"mcp": {"servers": {"arggon": {"type": "local", "command": ["arggon", "mcp"]}}}';

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Tolerant JSONC parse (task-opencode-v2-doctor): OpenCode configs may be
 * `opencode.jsonc` with `//`/`/* *\/` comments and trailing commas, which
 * `JSON.parse` rejects. Comments outside strings are stripped and trailing
 * commas before `}`/`]` dropped by one linear string-aware scan each, then
 * `JSON.parse` runs; malformed input returns null — doctor never throws on
 * adopter content and never rewrites it.
 */
function parseJsonc(text: string): unknown | null {
  let stripped = "";
  let inString = false;
  let escaped = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    if (inString) {
      stripped += ch;
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      stripped += ch;
      continue;
    }
    if (ch === "/" && text[i + 1] === "/") {
      while (i < text.length && text[i] !== "\n") i++;
      stripped += "\n";
      continue;
    }
    if (ch === "/" && text[i + 1] === "*") {
      i += 2;
      while (i < text.length && !(text[i] === "*" && text[i + 1] === "/")) i++;
      i++; // land on the closing '/'; the outer loop steps past it
      continue;
    }
    stripped += ch;
  }
  let json = "";
  inString = false;
  escaped = false;
  for (let i = 0; i < stripped.length; i++) {
    const ch = stripped[i]!;
    if (inString) {
      json += ch;
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') {
      inString = true;
      json += ch;
      continue;
    }
    if (ch === ",") {
      let j = i + 1;
      while (j < stripped.length && /\s/.test(stripped[j]!)) j++;
      if (stripped[j] === "}" || stripped[j] === "]") continue; // drop the trailing comma
    }
    json += ch;
  }
  try {
    return JSON.parse(json) as unknown;
  } catch {
    return null;
  }
}

/** Read + tolerant-parse a JSON(C) file; null when absent, unreadable, or malformed. */
function readJsonObject(absPath: string): Record<string, unknown> | null {
  let text: string;
  try {
    text = readFileSync(absPath, "utf8");
  } catch {
    return null;
  }
  const parsed = parseJsonc(text);
  return isJsonObject(parsed) ? parsed : null;
}

/** V1-shaped key hits in one parsed OpenCode config, sorted. */
function v1ShapedKeys(config: Record<string, unknown>): string[] {
  const keys: string[] = [];
  for (const key of OPENCODE_V1_KEYS) {
    if (Object.prototype.hasOwnProperty.call(config, key)) keys.push(key);
  }
  const mcp = config["mcp"];
  if (isJsonObject(mcp)) {
    for (const name of Object.keys(mcp)) {
      if (!OPENCODE_V2_MCP_KEYS.has(name)) keys.push(`mcp.${name}`);
    }
  }
  return keys.sort();
}

type NameList = { names: string[]; truncated: boolean };

/** Sorted `.md` stems in a fixed directory, capped. Never recurses, never throws. */
function listMarkdownNames(absDir: string): NameList {
  let entries: Dirent[];
  try {
    entries = readdirSync(absDir, { withFileTypes: true });
  } catch {
    return { names: [], truncated: false };
  }
  const names = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name.slice(0, -".md".length))
    .sort();
  return { names: names.slice(0, MAX_OPENCODE_NAMES), truncated: names.length > MAX_OPENCODE_NAMES };
}

/** Sorted directory names in a fixed directory, capped. Never recurses, never throws. */
function listDirNames(absDir: string): NameList {
  let entries: Dirent[];
  try {
    entries = readdirSync(absDir, { withFileTypes: true });
  } catch {
    return { names: [], truncated: false };
  }
  const names = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  return { names: names.slice(0, MAX_OPENCODE_NAMES), truncated: names.length > MAX_OPENCODE_NAMES };
}

/**
 * OpenCode integration probe (task-opencode-v2-doctor): pure read over fixed
 * paths — the four config candidates, `.mcp.json`, and one non-recursive
 * readdir each for `.opencode/agents`, `.opencode/commands`, `.agents/skills`.
 * Never throws, never writes; all lists are capped (MAX_OPENCODE_NAMES /
 * MAX_OPENCODE_V1_KEYS_PER_FILE).
 */
export function detectOpenCode(root: string): DoctorOpenCode {
  const configs: string[] = [];
  const findings: Array<{ file: string; keys: string[] }> = [];
  let v1Truncated = false;
  let native = false;
  for (const rel of OPENCODE_CONFIG_CANDIDATES) {
    const abs = join(root, ...rel.split("/"));
    if (!existsSync(abs)) continue;
    configs.push(rel);
    const parsed = readJsonObject(abs);
    if (parsed === null) continue; // present but unreadable/malformed
    const keys = v1ShapedKeys(parsed);
    if (keys.length > 0) {
      if (keys.length > MAX_OPENCODE_V1_KEYS_PER_FILE) {
        keys.length = MAX_OPENCODE_V1_KEYS_PER_FILE;
        v1Truncated = true;
      }
      findings.push({ file: rel, keys });
    }
    const mcp = parsed["mcp"];
    const servers = isJsonObject(mcp) ? mcp["servers"] : undefined;
    if (isJsonObject(servers) && Object.prototype.hasOwnProperty.call(servers, "arggon")) {
      native = true;
    }
  }

  const agents = listMarkdownNames(join(root, ".opencode", "agents"));
  const commands = listMarkdownNames(join(root, ".opencode", "commands"));
  const skills = listDirNames(join(root, ".agents", "skills"));
  const mcpJsonConfig = readJsonObject(join(root, ".mcp.json"));
  const mcpServers =
    mcpJsonConfig && isJsonObject(mcpJsonConfig["mcpServers"]) ? mcpJsonConfig["mcpServers"] : undefined;
  const mcpJson = mcpServers !== undefined && Object.prototype.hasOwnProperty.call(mcpServers, "arggon");

  return {
    configs,
    v1: { findings, truncated: v1Truncated },
    artifacts: {
      config: existsSync(join(root, "opencode.jsonc")),
      agents: agents.names,
      commands: commands.names,
      skills: skills.names,
      truncated: agents.truncated || commands.truncated || skills.truncated,
    },
    mcp: {
      native,
      mcpJson,
      hint: !native && mcpJson ? OPENCODE_MCP_HINT : null,
    },
  };
}

export type DoctorResult = {
  /** Repo root, or null when no tasks/.convention.yml was found. */
  root: string | null;
  initialized: boolean;
  /** Convention version from tasks/.convention.yml (0-3; 0 when missing). */
  conventionVersion: number;
  /**
   * Project name used for `{{PROJECT_NAME}}` renders this run
   * (bug-project-name-dir-derived, additive): the value recorded in
   * `x-generated.projectName`, or recovered from the on-disk generated docs
   * (legacy trees), or the directory basename for fresh scaffolds. `null`
   * when unrecoverable: name-sensitive outdated comparisons are SKIPPED for
   * that run instead of comparing against a guessed directory basename.
   */
  projectName: string | null;
  docs: DoctorDocs;
  tracker: {
    /** Total work items under tasks/. */
    items: number;
    /** Items with status todo. */
    todo: number;
  };
  /** Git state of the tree (additive; bug-init-git-doctor-blindspot). */
  git: DoctorGit;
  /**
   * OpenCode integration state (additive, task-opencode-v2-doctor): config
   * files, V1-shaped keys, generated seam artifacts (names only), and native
   * vs `.mcp.json`-only MCP registration. Report-only, bounded.
   */
  opencode: DoctorOpenCode;
  /**
   * Context-budget measurement (additive, task-adr0006-remeasure): present
   * only when `doctor --budget` is passed. Measures the ADR 0006 agent-facing
   * surfaces with the 2026-09-14 baseline method (fresh `init --full` in a
   * temp tree that is always deleted) — report-only, never touches this tree.
   */
  budget?: BudgetResult;
  /** Set when the budget measurement itself failed (doctor still exits 0). */
  budgetError?: string;
};

const ZERO_DOCS: DoctorDocs = {
  managed: 0,
  untouched: 0,
  modified: 0,
  acknowledged: 0,
  acknowledgedDrifted: 0,
  stale: 0,
  missing: 0,
  outdated: 0,
  outdatedDocs: [],
};

const NOT_A_REPO: DoctorGit = { isRepo: false, dirty: null, remote: null };

function gitProbe(args: string[], cwd: string): { ok: boolean; out: string } {
  try {
    return {
      ok: true,
      out: String(execFileSync("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }) ?? ""),
    };
  } catch {
    return { ok: false, out: "" };
  }
}

/** Best-effort git state report (bug-init-git-doctor-blindspot); never throws. */
export function gitState(cwd: string): DoctorGit {
  if (!gitProbe(["rev-parse", "--git-dir"], cwd).ok) return { ...NOT_A_REPO };
  const dirty = gitProbe(["status", "--porcelain"], cwd).out.trim().length > 0;
  let remote: string | null = null;
  const remotes = gitProbe(["remote"], cwd).out.split("\n").map((l) => l.trim()).filter(Boolean);
  const pick = remotes.includes("origin") ? "origin" : remotes[0];
  if (pick) {
    const url = gitProbe(["remote", "get-url", pick], cwd).out.trim();
    if (url) remote = url;
  }
  return { isRepo: true, dirty, remote };
}

/**
 * Best-effort budget measurement for `doctor --budget`: doctor stays exit-0
 * even if the measurement fails. Async because the MCP schema dimension
 * (task-schema-budget) fetches the live tools/list in-process. The caller
 * (cli.ts doctor action) attaches the result to the DoctorResult before
 * formatting, so runDoctor itself stays synchronous for its other callers.
 */
export async function measureBudgetForDoctor(): Promise<{ budget?: BudgetResult; budgetError?: string }> {
  try {
    return { budget: await measureBudget() };
  } catch (err) {
    return { budgetError: err instanceof Error ? err.message : String(err) };
  }
}

export function runDoctor(opts: {
  cwd: string;
  /**
   * Templates root override (task-doctor-outdated-bucket): the package
   * `templates/` dir doctor re-renders from. Defaults to the bundled dir;
   * tests point it at a mutable fixture copy to simulate upstream template
   * movement. Doctor never writes to it.
   */
  templatesRoot?: string;
}): DoctorResult {
  let tasksDir: string;
  let root: string;
  try {
    tasksDir = findTasksDir(opts.cwd);
    root = repoRootFromTasks(tasksDir);
  } catch {
    // Missing tree: a normal report, not a failure (task-doctor-command).
    // Budget, when requested, is attached by the caller (measureBudgetForDoctor).
    return {
      root: null,
      initialized: false,
      conventionVersion: 0,
      projectName: null,
      docs: { ...ZERO_DOCS },
      tracker: { items: 0, todo: 0 },
      git: gitState(opts.cwd),
      // No tasks/ tree, so cwd is the best root for the OpenCode probe — the
      // same directory gitState probes (task-opencode-v2-doctor).
      opencode: detectOpenCode(opts.cwd),
    };
  }

  const conventionVersion = readConventionVersion(root);
  const config = readConventionConfig(root);
  // Project-name resolution once per run (bug-project-name-dir-derived):
  // recorded state → legacy content recovery → fresh dir-basename fallback.
  const nameRes = resolveProjectName(root, {
    entries: config.generated,
    recorded: config.generatedProjectName,
  });
  const templatesDir = opts.templatesRoot ?? bundledTemplatesDir();
  const currentTemplates = new Set(currentGeneratedTemplatesFrom(templatesDir).map((t) => t.template));

  let untouched = 0;
  let modified = 0;
  let acknowledged = 0;
  let acknowledgedDrifted = 0;
  let stale = 0;
  let missing = 0;
  let outdated = 0;
  const outdatedDocs: string[] = [];
  const entries = Object.entries(config.generated);
  for (const [dest, entry] of entries) {
    const destAbs = join(root, ...dest.split("/"));
    if (!existsSync(destAbs)) {
      missing++;
      continue;
    }
    if (!currentTemplates.has(entry.template)) {
      stale++;
      continue;
    }
    let diskContent: string;
    try {
      diskContent = readFileSync(destAbs, "utf8");
    } catch {
      // Unreadable file: still acknowledged if acked, else modified; outdated
      // is undecidable either way.
      if (entry.acknowledged) acknowledged++;
      else modified++;
      continue;
    }
    // Outdated check (task-doctor-outdated-bucket): re-render the CURRENT
    // template exactly as init would (same resolution + placeholders) and
    // compare with the on-disk bytes. Pure read; a missing/unreadable
    // template renders null → not outdated. Applies to every local state
    // (untouched, modified, acked, acked-drifted): upstream moved regardless.
    // bug-project-name-dir-derived: the render uses the run's resolved
    // project name; when it is unrecoverable (`null`), the render is refused
    // → the name-sensitive comparison SKIPS (no false outdated signal from a
    // guessed directory basename).
    const render = renderGeneratedDoc({
      templatesDir,
      root,
      template: entry.template,
      dest,
      projectName: nameRes.name,
    });
    // bug-crlf-provenance-breakage: the render-vs-disk compare is
    // EOL-normalized, so a git-smudged CRLF working tree (`* text=auto
    // eol=crlf`) is not reported outdated when only the line endings differ.
    if (render !== null && normalizeEol(render) !== normalizeEol(diskContent)) {
      outdated++;
      outdatedDocs.push(dest);
    }
    if (entry.acknowledged) {
      // Acknowledged baseline (bug-ack-baseline-regen-loss): sanctioned
      // content — never a candidate for regeneration and never `modified`.
      // bug-ack-drift-promise: if the current bytes no longer match the
      // acked baseline, a hand edit landed after the ack — surface it in
      // the informational `acknowledgedDrifted` bucket.
      // bug-crlf-provenance-breakage: the match is EOL-tolerant in both
      // directions (LF-recorded state vs CRLF tree, and an ack recorded over
      // CRLF bytes vs an LF checkout) — only real content edits drift.
      if (entry.checksum && !checksumMatches(entry.checksum, diskContent)) {
        acknowledgedDrifted++;
      } else {
        acknowledged++;
      }
      continue;
    }
    if (entry.checksum && checksumMatches(entry.checksum, diskContent)) {
      untouched++;
    } else {
      modified++;
    }
  }

  const items = loadItems(tasksDir);
  return {
    root,
    initialized: true,
    conventionVersion,
    projectName: nameRes.name,
    docs: {
      managed: entries.length,
      untouched,
      modified,
      acknowledged,
      acknowledgedDrifted,
      stale,
      missing,
      outdated,
      outdatedDocs: outdatedDocs.sort(),
    },
    tracker: {
      items: items.length,
      todo: items.filter((item) => item.status === "todo").length,
    },
    git: gitState(root),
    opencode: detectOpenCode(root),
  };
}

/** One-line human summary of the git state: repo ✓/✗ + dirty + remote (sanitized — the URL is repo-controlled). */
function formatGitLine(git: DoctorGit): string {
  if (!git.isRepo) return "not a git repository (branch/worktree/push/PR flows unavailable)";
  const parts = ["repo", git.dirty ? "dirty" : "clean"];
  if (git.remote) parts.push(`remote ${sanitizeHumanText(git.remote)}`);
  else parts.push("no remote");
  return parts.join(", ");
}

/** Any OpenCode signal worth printing on a non-initialized tree? */
function hasOpenCodeSignal(opencode: DoctorOpenCode): boolean {
  return (
    opencode.configs.length > 0 ||
    opencode.artifacts.config ||
    opencode.artifacts.agents.length > 0 ||
    opencode.artifacts.commands.length > 0 ||
    opencode.artifacts.skills.length > 0 ||
    opencode.mcp.mcpJson
  );
}

/**
 * Bounded human lines for the OpenCode block (task-opencode-v2-doctor): a
 * one-line summary mirroring the JSON, plus a hint per finding class
 * (`V1-shaped` keys, `.mcp.json`-only registration). Never throws. Untrusted
 * config keys pass through `sanitizeHumanValue` before joining the hint line
 * (MINOR-1, PR #324 review).
 */
function formatOpenCodeLines(opencode: DoctorOpenCode): string[] {
  const seam =
    (opencode.artifacts.config ? 1 : 0) + opencode.artifacts.agents.length + opencode.artifacts.commands.length;
  const parts = [
    opencode.configs.length > 0 ? `config ${opencode.configs.join(", ")}` : "no config",
    seam > 0 ? `seam ${seam} artifact(s)` : "no seam artifacts",
    opencode.artifacts.skills.length > 0
      ? `${opencode.artifacts.skills.length} bundled skill(s)`
      : "no bundled skills",
    opencode.mcp.native ? "MCP native" : opencode.mcp.mcpJson ? "MCP only in .mcp.json" : "MCP not registered",
  ];
  const lines = [`  opencode: ${parts.join(", ")}`];
  if (opencode.v1.findings.length > 0) {
    const detail = opencode.v1.findings
      .map((f) => `${f.file} (${f.keys.map(sanitizeHumanValue).join(", ")})`)
      .join("; ");
    lines.push(
      `  hint: V1-shaped OpenCode config ${detail}${opencode.v1.truncated ? " (truncated)" : ""} — ` +
        "V2 expects MCP servers under mcp.servers and renamed/replaced several top-level keys",
    );
  }
  if (opencode.mcp.hint) lines.push(`  hint: ${opencode.mcp.hint}`);
  return lines;
}

/** Human-readable report (never writes; pairs with the doctor --json payload). */
export function formatDoctorReport(result: DoctorResult): string {
  if (!result.initialized) {
    const lines = ["arggon doctor: not initialized (no tasks/.convention.yml found) — run `arggon init`"];
    if (hasOpenCodeSignal(result.opencode)) lines.push(...formatOpenCodeLines(result.opencode));
    if (result.budget) lines.push(...formatBudgetLines(result.budget));
    return `${lines.join("\n")}\n`;
  }
  const lines = [
    `arggon doctor: initialized (convention v${result.conventionVersion}) at ${sanitizeHumanText(result.root ?? "null")}`,
    `  docs: ${result.docs.managed} managed, ${result.docs.untouched} untouched, ` +
      `${result.docs.modified} modified, ${result.docs.acknowledged} acknowledged, ` +
      `${result.docs.acknowledgedDrifted} acknowledgedDrifted, ` +
      `${result.docs.stale} stale, ${result.docs.missing} missing, ` +
      `${result.docs.outdated} outdated`,
    `  tracker: ${result.tracker.items} item(s), ${result.tracker.todo} todo`,
    `  git: ${formatGitLine(result.git)}`,
    ...formatOpenCodeLines(result.opencode),
  ];
  if (result.budget) {
    lines.push(...formatBudgetLines(result.budget));
  } else if (result.budgetError !== undefined) {
    lines.push(`  budget: measurement failed: ${sanitizeHumanText(result.budgetError)}`);
  }
  if (result.docs.acknowledgedDrifted > 0) {
    lines.push(
      "  note: " +
        `${result.docs.acknowledgedDrifted} acknowledged doc(s) drifted from the acked baseline ` +
        "(hand edit after `adopt --ack`) — still yours, never regenerated",
    );
  }
  if (result.projectName === null) {
    lines.push(
      "  note: project-name-unrecoverable — the project name could not be recovered " +
        "from x-generated.projectName or the generated docs; name-bearing outdated " +
        "comparisons were skipped (no false signals from the directory name)",
    );
  }
  if (result.docs.outdated > 0) {
    lines.push(
      "  hint: " +
        `${result.docs.outdated} doc(s) have newer templates — run ` +
        "`arggon init --dry-run` for the plan",
    );
  }
  if (result.docs.modified > 0) {
    lines.push(
      "  hint: re-run `arggon init --backup` to archive modified docs and regenerate them",
    );
  }
  return `${lines.join("\n")}\n`;
}
