/**
 * `arggon doctor` — installation state report (story-adoption-state,
 * task-doctor-command). Report-only, exit 0: answers "is ArggonManager
 * installed here, and in what shape" from the same sources init writes —
 * tasks/.convention.yml (convention version, x-generated provenance) and the
 * work-item tree (tracker counts). Never writes anything.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { readConventionConfig, readConventionVersion } from "./convention.js";
import {
  checksumMatches,
  currentGeneratedTemplatesFrom,
  normalizeEol,
  renderGeneratedDoc,
  resolveProjectName,
} from "./docs.js";
import { loadItems } from "./items.js";
import { measureBudget, formatBudgetLines, type BudgetResult } from "./measure.js";
import { findTasksDir, repoRootFromTasks, bundledTemplatesDir } from "./paths.js";

export type DoctorDocs = {
  /** Total x-generated provenance entries. */
  managed: number;
  /** Files whose checksum still matches the recorded one. */
  untouched: number;
  /** Files on disk whose checksum differs from the recorded one. */
  modified: number;
  /**
   * Entries acknowledged via `arggon adopt --ack` (bug-ack-baseline-regen-loss):
   * sanctioned-diverged baselines — healthy, and never regenerated by init.
   */
  acknowledged: number;
  /**
   * Acknowledged entries whose CURRENT checksum differs from the recorded
   * acked baseline (bug-ack-drift-promise): a hand edit landed after the ack.
   * Informational only — the file stays adopter-owned (never `modified`,
   * never regenerated by init); this bucket just makes the drift visible.
   */
  acknowledgedDrifted: number;
  /** State entries whose template no longer exists in the current bundle. */
  stale: number;
  /** State entries whose destination file is absent. */
  missing: number;
  /**
   * Managed docs whose CURRENT template render differs from the on-disk
   * content (task-doctor-outdated-bucket): the upstream template moved since
   * the doc was generated/acked, so it is not receiving upstream
   * improvements. Orthogonal to the untouched/modified/acknowledged buckets
   * (upstream moved regardless of local state); docs in `stale` (template no
   * longer generated) or `missing` are never outdated, and a missing or
   * unreadable template file counts as "cannot decide" — not outdated,
   * never a throw.
   */
  outdated: number;
  /**
   * Destinations counted in `outdated` (posix, relative to root) — the
   * per-destination detail behind the count.
   */
  outdatedDocs: string[];
};

/**
 * Git state of the target tree (bug-init-git-doctor-blindspot): report-only —
 * branch/worktree/push/PR flows and the pre-commit validate hook all depend on
 * git, so doctor surfaces whether they are even possible here. `dirty` and
 * `remote` are null when the tree is not a git repository.
 */
export type DoctorGit = {
  isRepo: boolean;
  /** Working tree has uncommitted changes (status --porcelain non-empty); null when not a repo. */
  dirty: boolean | null;
  /** URL of the `origin` remote (else the first remote); null when not a repo or no remote. */
  remote: string | null;
};

export type DoctorResult = {
  /** Repo root, or null when no tasks/.convention.yml was found. */
  root: string | null;
  initialized: boolean;
  /** Convention version from tasks/.convention.yml (0-3; 0 when missing). */
  conventionVersion: number;
  /**
   * Project name used for `{{PROJECT_NAME}}` renders this run
   * (bug-project-name-dir-derived, additive): the value recorded in
   * `x-generated.projectName`, or recovered from the on-disk generated docs
   * (legacy trees), or the directory basename for fresh scaffolds. `null`
   * when unrecoverable: name-sensitive outdated comparisons are SKIPPED for
   * that run instead of comparing against a guessed directory basename.
   */
  projectName: string | null;
  docs: DoctorDocs;
  tracker: {
    /** Total work items under tasks/. */
    items: number;
    /** Items with status todo. */
    todo: number;
  };
  /** Git state of the tree (additive; bug-init-git-doctor-blindspot). */
  git: DoctorGit;
  /**
   * Context-budget measurement (additive, task-adr0006-remeasure): present
   * only when `doctor --budget` is passed. Measures the ADR 0006 agent-facing
   * surfaces with the 2026-09-14 baseline method (fresh `init --full` in a
   * temp tree that is always deleted) — report-only, never touches this tree.
   */
  budget?: BudgetResult;
  /** Set when the budget measurement itself failed (doctor still exits 0). */
  budgetError?: string;
};

const ZERO_DOCS: DoctorDocs = {
  managed: 0,
  untouched: 0,
  modified: 0,
  acknowledged: 0,
  acknowledgedDrifted: 0,
  stale: 0,
  missing: 0,
  outdated: 0,
  outdatedDocs: [],
};

const NOT_A_REPO: DoctorGit = { isRepo: false, dirty: null, remote: null };

function gitProbe(args: string[], cwd: string): { ok: boolean; out: string } {
  try {
    return {
      ok: true,
      out: String(execFileSync("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }) ?? ""),
    };
  } catch {
    return { ok: false, out: "" };
  }
}

/** Best-effort git state report (bug-init-git-doctor-blindspot); never throws. */
export function gitState(cwd: string): DoctorGit {
  if (!gitProbe(["rev-parse", "--git-dir"], cwd).ok) return { ...NOT_A_REPO };
  const dirty = gitProbe(["status", "--porcelain"], cwd).out.trim().length > 0;
  let remote: string | null = null;
  const remotes = gitProbe(["remote"], cwd).out.split("\n").map((l) => l.trim()).filter(Boolean);
  const pick = remotes.includes("origin") ? "origin" : remotes[0];
  if (pick) {
    const url = gitProbe(["remote", "get-url", pick], cwd).out.trim();
    if (url) remote = url;
  }
  return { isRepo: true, dirty, remote };
}

/**
 * Best-effort budget measurement for `doctor --budget`: doctor stays exit-0
 * even if the measurement fails. Async because the MCP schema dimension
 * (task-schema-budget) fetches the live tools/list in-process. The caller
 * (cli.ts doctor action) attaches the result to the DoctorResult before
 * formatting, so runDoctor itself stays synchronous for its other callers.
 */
export async function measureBudgetForDoctor(): Promise<{ budget?: BudgetResult; budgetError?: string }> {
  try {
    return { budget: await measureBudget() };
  } catch (err) {
    return { budgetError: err instanceof Error ? err.message : String(err) };
  }
}

export function runDoctor(opts: {
  cwd: string;
  /**
   * Templates root override (task-doctor-outdated-bucket): the package
   * `templates/` dir doctor re-renders from. Defaults to the bundled dir;
   * tests point it at a mutable fixture copy to simulate upstream template
   * movement. Doctor never writes to it.
   */
  templatesRoot?: string;
}): DoctorResult {
  let tasksDir: string;
  let root: string;
  try {
    tasksDir = findTasksDir(opts.cwd);
    root = repoRootFromTasks(tasksDir);
  } catch {
    // Missing tree: a normal report, not a failure (task-doctor-command).
    // Budget, when requested, is attached by the caller (measureBudgetForDoctor).
    return {
      root: null,
      initialized: false,
      conventionVersion: 0,
      projectName: null,
      docs: { ...ZERO_DOCS },
      tracker: { items: 0, todo: 0 },
      git: gitState(opts.cwd),
    };
  }

  const conventionVersion = readConventionVersion(root);
  const config = readConventionConfig(root);
  // Project-name resolution once per run (bug-project-name-dir-derived):
  // recorded state → legacy content recovery → fresh dir-basename fallback.
  const nameRes = resolveProjectName(root, {
    entries: config.generated,
    recorded: config.generatedProjectName,
  });
  const templatesDir = opts.templatesRoot ?? bundledTemplatesDir();
  const currentTemplates = new Set(currentGeneratedTemplatesFrom(templatesDir).map((t) => t.template));

  let untouched = 0;
  let modified = 0;
  let acknowledged = 0;
  let acknowledgedDrifted = 0;
  let stale = 0;
  let missing = 0;
  let outdated = 0;
  const outdatedDocs: string[] = [];
  const entries = Object.entries(config.generated);
  for (const [dest, entry] of entries) {
    const destAbs = join(root, ...dest.split("/"));
    if (!existsSync(destAbs)) {
      missing++;
      continue;
    }
    if (!currentTemplates.has(entry.template)) {
      stale++;
      continue;
    }
    let diskContent: string;
    try {
      diskContent = readFileSync(destAbs, "utf8");
    } catch {
      // Unreadable file: still acknowledged if acked, else modified; outdated
      // is undecidable either way.
      if (entry.acknowledged) acknowledged++;
      else modified++;
      continue;
    }
    // Outdated check (task-doctor-outdated-bucket): re-render the CURRENT
    // template exactly as init would (same resolution + placeholders) and
    // compare with the on-disk bytes. Pure read; a missing/unreadable
    // template renders null → not outdated. Applies to every local state
    // (untouched, modified, acked, acked-drifted): upstream moved regardless.
    // bug-project-name-dir-derived: the render uses the run's resolved
    // project name; when it is unrecoverable (`null`), the render is refused
    // → the name-sensitive comparison SKIPS (no false outdated signal from a
    // guessed directory basename).
    const render = renderGeneratedDoc({
      templatesDir,
      root,
      template: entry.template,
      dest,
      projectName: nameRes.name,
    });
    // bug-crlf-provenance-breakage: the render-vs-disk compare is
    // EOL-normalized, so a git-smudged CRLF working tree (`* text=auto
    // eol=crlf`) is not reported outdated when only the line endings differ.
    if (render !== null && normalizeEol(render) !== normalizeEol(diskContent)) {
      outdated++;
      outdatedDocs.push(dest);
    }
    if (entry.acknowledged) {
      // Acknowledged baseline (bug-ack-baseline-regen-loss): sanctioned
      // content — never a candidate for regeneration and never `modified`.
      // bug-ack-drift-promise: if the current bytes no longer match the
      // acked baseline, a hand edit landed after the ack — surface it in
      // the informational `acknowledgedDrifted` bucket.
      // bug-crlf-provenance-breakage: the match is EOL-tolerant in both
      // directions (LF-recorded state vs CRLF tree, and an ack recorded over
      // CRLF bytes vs an LF checkout) — only real content edits drift.
      if (entry.checksum && !checksumMatches(entry.checksum, diskContent)) {
        acknowledgedDrifted++;
      } else {
        acknowledged++;
      }
      continue;
    }
    if (entry.checksum && checksumMatches(entry.checksum, diskContent)) {
      untouched++;
    } else {
      modified++;
    }
  }

  const items = loadItems(tasksDir);
  return {
    root,
    initialized: true,
    conventionVersion,
    projectName: nameRes.name,
    docs: {
      managed: entries.length,
      untouched,
      modified,
      acknowledged,
      acknowledgedDrifted,
      stale,
      missing,
      outdated,
      outdatedDocs: outdatedDocs.sort(),
    },
    tracker: {
      items: items.length,
      todo: items.filter((item) => item.status === "todo").length,
    },
    git: gitState(root),
  };
}

/** One-line human summary of the git state: repo ✓/✗ + dirty + remote. */
function formatGitLine(git: DoctorGit): string {
  if (!git.isRepo) return "not a git repository (branch/worktree/push/PR flows unavailable)";
  const parts = ["repo", git.dirty ? "dirty" : "clean"];
  if (git.remote) parts.push(`remote ${git.remote}`);
  else parts.push("no remote");
  return parts.join(", ");
}

/** Human-readable report (never writes; pairs with the doctor --json payload). */
export function formatDoctorReport(result: DoctorResult): string {
  if (!result.initialized) {
    const head = "arggon doctor: not initialized (no tasks/.convention.yml found) — run `arggon init`\n";
    if (result.budget) return head + `${formatBudgetLines(result.budget).join("\n")}\n`;
    return head;
  }
  const lines = [
    `arggon doctor: initialized (convention v${result.conventionVersion}) at ${result.root}`,
    `  docs: ${result.docs.managed} managed, ${result.docs.untouched} untouched, ` +
      `${result.docs.modified} modified, ${result.docs.acknowledged} acknowledged, ` +
      `${result.docs.acknowledgedDrifted} acknowledgedDrifted, ` +
      `${result.docs.stale} stale, ${result.docs.missing} missing, ` +
      `${result.docs.outdated} outdated`,
    `  tracker: ${result.tracker.items} item(s), ${result.tracker.todo} todo`,
    `  git: ${formatGitLine(result.git)}`,
  ];
  if (result.budget) {
    lines.push(...formatBudgetLines(result.budget));
  } else if (result.budgetError !== undefined) {
    lines.push(`  budget: measurement failed: ${result.budgetError}`);
  }
  if (result.docs.acknowledgedDrifted > 0) {
    lines.push(
      "  note: " +
        `${result.docs.acknowledgedDrifted} acknowledged doc(s) drifted from the acked baseline ` +
        "(hand edit after `adopt --ack`) — still yours, never regenerated",
    );
  }
  if (result.projectName === null) {
    lines.push(
      "  note: project-name-unrecoverable — the project name could not be recovered " +
        "from x-generated.projectName or the generated docs; name-bearing outdated " +
        "comparisons were skipped (no false signals from the directory name)",
    );
  }
  if (result.docs.outdated > 0) {
    lines.push(
      "  hint: " +
        `${result.docs.outdated} doc(s) have newer templates — run ` +
        "`arggon init --dry-run` for the plan",
    );
  }
  if (result.docs.modified > 0) {
    lines.push(
      "  hint: re-run `arggon init --backup` to archive modified docs and regenerate them",
    );
  }
  return `${lines.join("\n")}\n`;
}
