/**
 * `arggon doctor` — installation state report (story-adoption-state,
 * task-doctor-command). Report-only, exit 0: answers "is ArggonManager
 * installed here, and in what shape" from the same sources init writes —
 * tasks/.convention.yml (convention version, x-generated provenance) and the
 * work-item tree (tracker counts). Never writes anything.
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { readConventionConfig, readConventionVersion } from "./convention.js";
import { checksumOf, currentGeneratedTemplates } from "./docs.js";
import { loadItems } from "./items.js";
import { measureBudget, formatBudgetLines, type BudgetResult } from "./measure.js";
import { findTasksDir, repoRootFromTasks } from "./paths.js";

export type DoctorDocs = {
  /** Total x-generated provenance entries. */
  managed: number;
  /** Files whose checksum still matches the recorded one. */
  untouched: number;
  /** Files on disk whose checksum differs from the recorded one. */
  modified: number;
  /**
   * Entries acknowledged via `arggon adopt --ack` (bug-ack-baseline-regen-loss):
   * sanctioned-diverged baselines — healthy, and never regenerated by init.
   */
  acknowledged: number;
  /**
   * Acknowledged entries whose CURRENT checksum differs from the recorded
   * acked baseline (bug-ack-drift-promise): a hand edit landed after the ack.
   * Informational only — the file stays adopter-owned (never `modified`,
   * never regenerated by init); this bucket just makes the drift visible.
   */
  acknowledgedDrifted: number;
  /** State entries whose template no longer exists in the current bundle. */
  stale: number;
  /** State entries whose destination file is absent. */
  missing: number;
};

/**
 * Git state of the target tree (bug-init-git-doctor-blindspot): report-only —
 * branch/worktree/push/PR flows and the pre-commit validate hook all depend on
 * git, so doctor surfaces whether they are even possible here. `dirty` and
 * `remote` are null when the tree is not a git repository.
 */
export type DoctorGit = {
  isRepo: boolean;
  /** Working tree has uncommitted changes (status --porcelain non-empty); null when not a repo. */
  dirty: boolean | null;
  /** URL of the `origin` remote (else the first remote); null when not a repo or no remote. */
  remote: string | null;
};

export type DoctorResult = {
  /** Repo root, or null when no tasks/.convention.yml was found. */
  root: string | null;
  initialized: boolean;
  /** Convention version from tasks/.convention.yml (0-3; 0 when missing). */
  conventionVersion: number;
  docs: DoctorDocs;
  tracker: {
    /** Total work items under tasks/. */
    items: number;
    /** Items with status todo. */
    todo: number;
  };
  /** Git state of the tree (additive; bug-init-git-doctor-blindspot). */
  git: DoctorGit;
  /**
   * Context-budget measurement (additive, task-adr0006-remeasure): present
   * only when `doctor --budget` is passed. Measures the ADR 0006 agent-facing
   * surfaces with the 2026-09-14 baseline method (fresh `init --full` in a
   * temp tree that is always deleted) — report-only, never touches this tree.
   */
  budget?: BudgetResult;
  /** Set when the budget measurement itself failed (doctor still exits 0). */
  budgetError?: string;
};

const ZERO_DOCS: DoctorDocs = {
  managed: 0,
  untouched: 0,
  modified: 0,
  acknowledged: 0,
  acknowledgedDrifted: 0,
  stale: 0,
  missing: 0,
};

const NOT_A_REPO: DoctorGit = { isRepo: false, dirty: null, remote: null };

function gitProbe(args: string[], cwd: string): { ok: boolean; out: string } {
  try {
    return {
      ok: true,
      out: String(execFileSync("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" }) ?? ""),
    };
  } catch {
    return { ok: false, out: "" };
  }
}

/** Best-effort git state report (bug-init-git-doctor-blindspot); never throws. */
export function gitState(cwd: string): DoctorGit {
  if (!gitProbe(["rev-parse", "--git-dir"], cwd).ok) return { ...NOT_A_REPO };
  const dirty = gitProbe(["status", "--porcelain"], cwd).out.trim().length > 0;
  let remote: string | null = null;
  const remotes = gitProbe(["remote"], cwd).out.split("\n").map((l) => l.trim()).filter(Boolean);
  const pick = remotes.includes("origin") ? "origin" : remotes[0];
  if (pick) {
    const url = gitProbe(["remote", "get-url", pick], cwd).out.trim();
    if (url) remote = url;
  }
  return { isRepo: true, dirty, remote };
}

/** Best-effort budget measurement: doctor stays exit-0 even if it fails. */
function tryMeasureBudget(): { budget?: BudgetResult; budgetError?: string } {
  try {
    return { budget: measureBudget() };
  } catch (err) {
    return { budgetError: err instanceof Error ? err.message : String(err) };
  }
}

export function runDoctor(opts: { cwd: string; budget?: boolean }): DoctorResult {
  // Measured up front (both the initialized and not-initialized report paths
  // include it): the budget surfaces come from a throwaway temp tree, not
  // from the tree being examined.
  const budgetPart = opts.budget === true ? tryMeasureBudget() : {};
  let tasksDir: string;
  let root: string;
  try {
    tasksDir = findTasksDir(opts.cwd);
    root = repoRootFromTasks(tasksDir);
  } catch {
    // Missing tree: a normal report, not a failure (task-doctor-command).
    return {
      root: null,
      initialized: false,
      conventionVersion: 0,
      docs: { ...ZERO_DOCS },
      tracker: { items: 0, todo: 0 },
      git: gitState(opts.cwd),
      ...budgetPart,
    };
  }

  const conventionVersion = readConventionVersion(root);
  const config = readConventionConfig(root);
  const currentTemplates = new Set(currentGeneratedTemplates().map((t) => t.template));

  let untouched = 0;
  let modified = 0;
  let acknowledged = 0;
  let acknowledgedDrifted = 0;
  let stale = 0;
  let missing = 0;
  const entries = Object.entries(config.generated);
  for (const [dest, entry] of entries) {
    const destAbs = join(root, ...dest.split("/"));
    if (!existsSync(destAbs)) {
      missing++;
      continue;
    }
    if (!currentTemplates.has(entry.template)) {
      stale++;
      continue;
    }
    if (entry.acknowledged) {
      // Acknowledged baseline (bug-ack-baseline-regen-loss): sanctioned
      // content — never a candidate for regeneration and never `modified`.
      // bug-ack-drift-promise: if the current bytes no longer match the
      // acked baseline, a hand edit landed after the ack — surface it in
      // the informational `acknowledgedDrifted` bucket.
      let actual: string;
      try {
        actual = checksumOf(readFileSync(destAbs, "utf8"));
      } catch {
        // Unreadable acked file: still acknowledged, drift undecidable.
        acknowledged++;
        continue;
      }
      if (entry.checksum && actual !== entry.checksum) {
        acknowledgedDrifted++;
      } else {
        acknowledged++;
      }
      continue;
    }
    let actual: string;
    try {
      actual = checksumOf(readFileSync(destAbs, "utf8"));
    } catch {
      modified++;
      continue;
    }
    if (entry.checksum && actual === entry.checksum) {
      untouched++;
    } else {
      modified++;
    }
  }

  const items = loadItems(tasksDir);
  return {
    root,
    initialized: true,
    conventionVersion,
    docs: {
      managed: entries.length,
      untouched,
      modified,
      acknowledged,
      acknowledgedDrifted,
      stale,
      missing,
    },
    tracker: {
      items: items.length,
      todo: items.filter((item) => item.status === "todo").length,
    },
    git: gitState(root),
    ...budgetPart,
  };
}

/** One-line human summary of the git state: repo ✓/✗ + dirty + remote. */
function formatGitLine(git: DoctorGit): string {
  if (!git.isRepo) return "not a git repository (branch/worktree/push/PR flows unavailable)";
  const parts = ["repo", git.dirty ? "dirty" : "clean"];
  if (git.remote) parts.push(`remote ${git.remote}`);
  else parts.push("no remote");
  return parts.join(", ");
}

/** Human-readable report (never writes; pairs with the doctor --json payload). */
export function formatDoctorReport(result: DoctorResult): string {
  if (!result.initialized) {
    const head = "arggon doctor: not initialized (no tasks/.convention.yml found) — run `arggon init`\n";
    if (result.budget) return head + `${formatBudgetLines(result.budget).join("\n")}\n`;
    return head;
  }
  const lines = [
    `arggon doctor: initialized (convention v${result.conventionVersion}) at ${result.root}`,
    `  docs: ${result.docs.managed} managed, ${result.docs.untouched} untouched, ` +
      `${result.docs.modified} modified, ${result.docs.acknowledged} acknowledged, ` +
      `${result.docs.acknowledgedDrifted} acknowledgedDrifted, ` +
      `${result.docs.stale} stale, ${result.docs.missing} missing`,
    `  tracker: ${result.tracker.items} item(s), ${result.tracker.todo} todo`,
    `  git: ${formatGitLine(result.git)}`,
  ];
  if (result.budget) {
    lines.push(...formatBudgetLines(result.budget));
  } else if (result.budgetError !== undefined) {
    lines.push(`  budget: measurement failed: ${result.budgetError}`);
  }
  if (result.docs.acknowledgedDrifted > 0) {
    lines.push(
      "  note: " +
        `${result.docs.acknowledgedDrifted} acknowledged doc(s) drifted from the acked baseline ` +
        "(hand edit after `adopt --ack`) — still yours, never regenerated",
    );
  }
  if (result.docs.modified > 0) {
    lines.push(
      "  hint: re-run `arggon init --backup` to archive modified docs and regenerate them",
    );
  }
  return `${lines.join("\n")}\n`;
}
