import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { stampGeneratedContent } from "./docs.js";

// plan-opencode2-009 W2 (T6): opencode/plugins/arggon/index.ts is the single
// committed source; .opencode/plugins/arggon/index.ts is a gitignored derived
// copy (generated marker + source), exactly like the bundled skill
// (skill-copy.test.ts precedent). This test REGENERATES the copy whenever it
// is absent or mismatched — a stale local copy (e.g. after merging a PR that
// changed the source) can never fail the suite; the copy is derived, the
// source is the truth. The assertion remains the last line of defense: it
// validates the GENERATED bytes (the `//` marker contract included), plus a
// determinism guard (regenerating twice yields identical bytes).
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const SOURCE = "opencode/plugins/arggon/index.ts";
const DEST = ".opencode/plugins/arggon/index.ts";

function expectedCopy(source: string): string {
  return stampGeneratedContent(DEST, SOURCE, source);
}

describe("bundled plugin copy parity", () => {
  it("regenerates .opencode/plugins/arggon/index.ts from the source, deterministically", () => {
    const source = readFileSync(join(repoRoot, SOURCE), "utf8");
    const copyPath = join(repoRoot, DEST);
    const expected = expectedCopy(source);
    // Pin the marker contract independently of the stamp implementation: the
    // generated copy starts with the `//` provenance line naming the source.
    expect(expected.startsWith(`// arggon:generated template="${SOURCE}"\n`)).toBe(true);
    if (!existsSync(copyPath) || readFileSync(copyPath, "utf8") !== expected) {
      mkdirSync(dirname(copyPath), { recursive: true });
      writeFileSync(copyPath, expected);
    }
    // determinism guard: regeneration is a pure function of the source
    expect(expectedCopy(readFileSync(join(repoRoot, SOURCE), "utf8"))).toBe(
      readFileSync(copyPath, "utf8"),
    );
  });
});
