import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { BUNDLED_SKILLS, generatedMarker } from "./docs.js";

// task-adr0006-docs-budget: skills/arggon-cli/SKILL.md is the single committed
// source; .agents/skills/arggon-cli/SKILL.md is a gitignored derived copy
// (marker + source). task-skill-copy-pretest-sync: this test REGENERATES the
// copy whenever it is absent or mismatched — a stale local copy (e.g. after
// merging a PR that changed the source) can never fail the suite; the copy is
// derived, the source is the truth. The assertion remains the last line of
// defense: it validates the GENERATED bytes, plus a determinism guard
// (regenerating twice yields identical bytes).
//
// task-opencode2-methodology (W5): the same parity contract covers EVERY file
// in BUNDLED_SKILLS — the arggon-cli umbrella, its references/ (read on demand
// by V2 sessions) and the arggon-upgrade skill — and every file committed
// under skills/arggon-cli/references/ must be in that list, so a reference
// cannot ship unbundled.
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function sourceBytes(source: string): string {
  return readFileSync(join(repoRoot, ...source.split("/")), "utf8");
}

function expectedCopy(source: string): string {
  return `${generatedMarker(source)}\n${sourceBytes(source)}`;
}

describe("bundled skill copy parity", () => {
  for (const { source, dest } of BUNDLED_SKILLS) {
    it(`regenerates ${dest} from the source, deterministically`, () => {
      const copyPath = join(repoRoot, ...dest.split("/"));
      const expected = expectedCopy(source);
      if (!existsSync(copyPath) || readFileSync(copyPath, "utf8") !== expected) {
        mkdirSync(dirname(copyPath), { recursive: true });
        writeFileSync(copyPath, expected);
      }
      // determinism guard: regeneration is a pure function of the source
      expect(expectedCopy(source)).toBe(readFileSync(copyPath, "utf8"));
    });
  }

  it("bundles every committed file under skills/arggon-cli/references/", () => {
    const referencesDir = join(repoRoot, "skills/arggon-cli/references");
    const committed = readdirSync(referencesDir).filter((name) => name.endsWith(".md"));
    expect(committed.length).toBeGreaterThan(0);
    const bundledSources = BUNDLED_SKILLS.map((s) => s.source);
    for (const name of committed) {
      expect(bundledSources, `${name} is not in BUNDLED_SKILLS`).toContain(
        `skills/arggon-cli/references/${name}`,
      );
    }
  });
});
