import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { generatedMarker } from "./docs.js";

// task-adr0006-docs-budget: skills/arggon-cli/SKILL.md is the single committed
// source; .agents/skills/arggon-cli/SKILL.md is a gitignored derived copy
// (marker + source). task-skill-copy-pretest-sync: this test REGENERATES the
// copy whenever it is absent or mismatched — a stale local copy (e.g. after
// merging a PR that changed the source) can never fail the suite; the copy is
// derived, the source is the truth. The assertion remains the last line of
// defense: it validates the GENERATED bytes, plus a determinism guard
// (regenerating twice yields identical bytes).
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function expectedCopy(source: string): string {
  return `${generatedMarker("skills/arggon-cli/SKILL.md")}\n${source}`;
}

describe("bundled skill copy parity", () => {
  it("regenerates .agents/skills/arggon-cli/SKILL.md from the source, deterministically", () => {
    const source = readFileSync(join(repoRoot, "skills/arggon-cli/SKILL.md"), "utf8");
    const copyPath = join(repoRoot, ".agents/skills/arggon-cli/SKILL.md");
    const expected = expectedCopy(source);
    if (!existsSync(copyPath) || readFileSync(copyPath, "utf8") !== expected) {
      mkdirSync(dirname(copyPath), { recursive: true });
      writeFileSync(copyPath, expected);
    }
    // determinism guard: regeneration is a pure function of the source
    expect(expectedCopy(readFileSync(join(repoRoot, "skills/arggon-cli/SKILL.md"), "utf8"))).toBe(
      readFileSync(copyPath, "utf8"),
    );
  });
});
